#include "cuda_manager.h"

#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QProcess>
#include <QRegularExpression>
#include <QTextStream>
#include <QVariantMap>

namespace aurum::settings {

namespace {

constexpr auto kInstallRoot = "/usr/local";
constexpr auto kActiveLink  = "/usr/local/cuda";
constexpr auto kUserEnvSubpath = "/aurum/cuda.env";

QString user_env_path() {
    return qEnvironmentVariable("XDG_CONFIG_HOME",
                                QDir::homePath() + "/.config")
         + kUserEnvSubpath;
}

QString read_user_active_version() {
    QFile f(user_env_path());
    if (!f.open(QIODevice::ReadOnly | QIODevice::Text)) return {};
    static const QRegularExpression re(R"(/usr/local/cuda-([\d.]+))");
    while (!f.atEnd()) {
        const auto line = QString::fromUtf8(f.readLine());
        const auto m = re.match(line);
        if (m.hasMatch()) return m.captured(1);
    }
    return {};
}

QString driver_version_via_nvidia_smi() {
    QProcess p;
    p.start("nvidia-smi", {"--query-gpu=driver_version", "--format=csv,noheader"});
    if (!p.waitForFinished(800)) return {};
    return QString::fromUtf8(p.readAllStandardOutput()).trimmed();
}

QString resolve_symlink(const QString& path) {
    QFileInfo fi(path);
    if (!fi.exists() || !fi.isSymLink()) return {};
    return fi.symLinkTarget();
}

} // namespace

CudaManager::CudaManager(QObject* parent) : QObject(parent) {
    scan();
}

void CudaManager::refresh() { scan(); emit toolkitsChanged(); }

void CudaManager::scan() {
    m_toolkits.clear();
    m_systemActive.clear();
    m_userActive.clear();

    // Detect installed toolkits under /usr/local/cuda-<version>.
    QDir root(kInstallRoot);
    static const QRegularExpression cuda_dir(R"(^cuda-([\d.]+)$)");
    const auto entries = root.entryInfoList(QDir::Dirs | QDir::NoDotAndDotDot,
                                            QDir::Name);
    QStringList versions;
    for (const auto& fi : entries) {
        const auto m = cuda_dir.match(fi.fileName());
        if (m.hasMatch())
            versions << m.captured(1);
    }
    // Reverse so the newest version is listed first.
    std::reverse(versions.begin(), versions.end());

    const auto active_target = resolve_symlink(kActiveLink);
    static const QRegularExpression active_re(R"(cuda-([\d.]+))");
    const auto sa = active_re.match(active_target);
    if (sa.hasMatch()) m_systemActive = sa.captured(1);

    m_userActive    = read_user_active_version();
    m_driverVersion = driver_version_via_nvidia_smi();

    for (const auto& v : versions) {
        m_toolkits << QVariantMap{
            {"version",        v},
            {"path",           QString("/usr/local/cuda-") + v},
            {"isSystemActive", v == m_systemActive},
            {"isUserActive",   v == m_userActive},
        };
    }
}

bool CudaManager::setUserActive(const QString& version) {
    const QString tk_path = QString("/usr/local/cuda-") + version;
    if (!QFileInfo::exists(tk_path)) return false;

    QDir().mkpath(QFileInfo(user_env_path()).absolutePath());
    QFile f(user_env_path());
    if (!f.open(QIODevice::WriteOnly | QIODevice::Truncate)) return false;
    QTextStream out(&f);
    // Sourced by /etc/profile.d/aurum-dl.sh.
    out << "# Auto-generated by aurum-settings; do not edit by hand.\n"
        << "export CUDA_HOME=\""    << tk_path << "\"\n"
        << "export CUDA_PATH=\""    << tk_path << "\"\n"
        << "export PATH=\""         << tk_path << "/bin:${PATH}\"\n"
        << "export LD_LIBRARY_PATH=\"" << tk_path << "/lib64:${LD_LIBRARY_PATH:-}\"\n";
    refresh();
    return true;
}

bool CudaManager::setSystemActive(const QString& version) {
    const QString tk_path = QString("/usr/local/cuda-") + version;
    if (!QFileInfo::exists(tk_path)) return false;

    // We don't run as root. Hand off to pkexec + a helper that's allowed via a
    // polkit rule shipped at /usr/share/polkit-1/actions/org.aurumos.settings.policy.
    QProcess p;
    p.start("pkexec", {"/usr/local/libexec/aurum-cuda-switch", version});
    if (!p.waitForFinished(8000)) return false;
    refresh();
    return p.exitCode() == 0;
}

} // namespace aurum::settings
