#!/usr/bin/env bash
# ==============================================================================
# AurumOS hardware profile auto-detection (Wave 8 — Agent G)
#
# Probes VRAM + RAM + GPU name, picks one of four tiers, and writes a
# bash-sourceable /etc/aurum/profile.conf consumed by every Wave 8/9 launcher
# (vLLM, Unsloth, ComfyUI, Continue.dev, etc.) and the C++ ProfileClient.
#
# Tiers:
#   lite        — VRAM 0       , RAM <16GB → CPU-only, tiny models
#   standard    — VRAM 6-12GB  , RAM 16-32GB → RTX 5060/4060 (the 80% target)
#   pro         — VRAM 12-16GB , RAM 32-64GB → RTX 4070/4080
#   workstation — VRAM 24GB+   , RAM 64GB+  → RTX 4090, A6000, dual-GPU
#
# Usage:
#   00-detect-profile.sh            → writes /etc/aurum/profile.conf
#   00-detect-profile.sh --print    → dumps resolved KEY=VALUE to stdout
#
# Honors $AURUM_PROFILE as a hard override (skips tier classification but still
# fills in the rest of the keys from probed hardware).
# ==============================================================================
set -euo pipefail

CONF_PATH="${AURUM_PROFILE_CONF:-/etc/aurum/profile.conf}"

# --- Probe hardware ----------------------------------------------------------
# nvidia-smi is absent in the Docker preview and CPU-only laptops; both must
# yield VRAM=0 and fall into the `lite` tier without erroring. We swallow
# stderr and treat empty/non-numeric output as zero.
probe_vram_mb() {
    local out
    out=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits 2>/dev/null | head -1 | tr -d ' \r\n' || true)
    if [[ -z "${out}" || ! "${out}" =~ ^[0-9]+$ ]]; then
        echo 0
    else
        echo "${out}"
    fi
}

probe_gpu_name() {
    local out
    out=$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | head -1 | sed 's/^ *//;s/ *$//' || true)
    if [[ -z "${out}" ]]; then
        echo "none"
    else
        echo "${out}"
    fi
}

probe_ram_gb() {
    # /proc/meminfo MemTotal is in kB; integer-divide twice to GB.
    awk '/^MemTotal:/ {print int($2/1024/1024)}' /proc/meminfo 2>/dev/null || echo 0
}

probe_has_cuda() {
    # Presence of nvidia-smi AND a non-zero VRAM result is the loosest possible
    # "is there a usable CUDA-capable GPU?" check. Wave 8 launchers care about
    # the boolean — they don't drive any CUDA toolkit selection themselves.
    if command -v nvidia-smi >/dev/null 2>&1 && [[ "$(probe_vram_mb)" -gt 0 ]]; then
        echo 1
    else
        echo 0
    fi
}

# --- Classify into tier ------------------------------------------------------
classify_profile() {
    local vram_mb="$1" ram_gb="$2"
    # Honor env override unconditionally (used for debugging / power-user pin).
    if [[ -n "${AURUM_PROFILE:-}" ]]; then
        echo "${AURUM_PROFILE}"
        return
    fi

    # Workstation: 24GB+ VRAM (RTX 4090, A6000, dual-GPU summed via memory.total
    # which on multi-GPU still reports per-card — we conservatively look at the
    # first GPU only; multi-GPU users typically also have ≥64GB RAM so the RAM
    # gate is a sanity-check secondary signal).
    if (( vram_mb >= 24000 )) || (( ram_gb >= 64 )); then
        # Both conditions trigger workstation; either alone is enough since a
        # 24GB GPU on a 32GB host is still a workstation-class user, and a
        # 64GB+ RAM box without GPU still benefits from larger CPU batch sizes.
        if (( vram_mb >= 24000 )) && (( ram_gb >= 32 )); then
            echo "workstation"; return
        fi
        if (( vram_mb >= 24000 )); then echo "workstation"; return; fi
        # Else fall through: lots of RAM but no/small GPU is still pro at best.
    fi

    # Pro: 12-16GB VRAM range AND at least 32GB RAM.
    if (( vram_mb >= 12000 )) && (( ram_gb >= 32 )); then
        echo "pro"; return
    fi

    # Standard: the 80% target — RTX 5060/4060/3060 class (8GB), 16-32GB RAM.
    # We accept VRAM 6-16GB here so a 6GB 3050 still gets `standard` not `lite`.
    if (( vram_mb >= 6000 )) && (( ram_gb >= 16 )); then
        echo "standard"; return
    fi

    # Lite: anything below — CPU-only, low RAM laptops, the Docker preview.
    echo "lite"
}

# --- Tier → defaults table ---------------------------------------------------
# Centralised so HardwarePanel.qml's "what this profile installs" table and the
# launcher scripts agree on every value. Output is emitted as KEY=VALUE lines.
emit_profile_keys() {
    local tier="$1" vram_mb="$2" ram_gb="$3" gpu_name="$4" has_cuda="$5"

    cat <<EOF
# /etc/aurum/profile.conf — generated by 00-detect-profile.sh
# Do not edit by hand; regenerated on every boot by aurum-detect-profile.service.
# Override the tier by setting AURUM_PROFILE in /etc/environment before boot.
AURUM_PROFILE=${tier}
AURUM_VRAM_MB=${vram_mb}
AURUM_RAM_GB=${ram_gb}
AURUM_GPU_NAME="${gpu_name}"
AURUM_HAS_CUDA=${has_cuda}
EOF

    case "${tier}" in
      lite)
        cat <<'EOF'
AURUM_OLLAMA_DEFAULT=qwen2.5-coder:1.5b
AURUM_OLLAMA_CHAT=qwen2.5:1.5b
AURUM_COMFYUI_FLAGS="--cpu --use-pytorch-cross-attention"
AURUM_VLLM_DEFAULT_ARGS="--device cpu --max-model-len 2048"
AURUM_UNSLOTH_RECIPE=qlora-4bit-1b
AURUM_SD_MODEL=sd15-int8
AURUM_WHISPER_MODEL=tiny
AURUM_YOLO_MODEL=yolov11n
AURUM_SAM_MODEL=sam2-tiny
AURUM_LLAVA_MODEL=llava-phi-int4
EOF
        ;;
      standard)
        cat <<'EOF'
AURUM_OLLAMA_DEFAULT=qwen2.5-coder:7b
AURUM_OLLAMA_CHAT=qwen2.5:7b
AURUM_COMFYUI_FLAGS="--medvram --use-pytorch-cross-attention"
AURUM_VLLM_DEFAULT_ARGS="--quantization awq --max-model-len 8192 --gpu-memory-utilization 0.85"
AURUM_UNSLOTH_RECIPE=qlora-4bit-7b
AURUM_SD_MODEL=sdxl-turbo-int8
AURUM_WHISPER_MODEL=small
AURUM_YOLO_MODEL=yolov11s
AURUM_SAM_MODEL=sam2-base
AURUM_LLAVA_MODEL=llava-7b-int4
EOF
        ;;
      pro)
        cat <<'EOF'
AURUM_OLLAMA_DEFAULT=qwen2.5-coder:14b
AURUM_OLLAMA_CHAT=qwen2.5:14b
AURUM_COMFYUI_FLAGS="--highvram --use-pytorch-cross-attention"
AURUM_VLLM_DEFAULT_ARGS="--quantization awq --max-model-len 16384 --gpu-memory-utilization 0.90"
AURUM_UNSLOTH_RECIPE=qlora-4bit-14b
AURUM_SD_MODEL=sdxl-fp16
AURUM_WHISPER_MODEL=medium
AURUM_YOLO_MODEL=yolov11m
AURUM_SAM_MODEL=sam2-large
AURUM_LLAVA_MODEL=llava-13b-int4
EOF
        ;;
      workstation)
        cat <<'EOF'
AURUM_OLLAMA_DEFAULT=qwen2.5-coder:32b
AURUM_OLLAMA_CHAT=qwen2.5:32b
AURUM_COMFYUI_FLAGS="--highvram --use-pytorch-cross-attention --bf16-vae"
AURUM_VLLM_DEFAULT_ARGS="--max-model-len 32768 --gpu-memory-utilization 0.92 --tensor-parallel-size 1"
AURUM_UNSLOTH_RECIPE=qlora-4bit-32b
AURUM_SD_MODEL=sdxl-fp16
AURUM_WHISPER_MODEL=large-v3
AURUM_YOLO_MODEL=yolov11x
AURUM_SAM_MODEL=sam2-large
AURUM_LLAVA_MODEL=llava-34b-int4
EOF
        ;;
      *)
        echo "# unknown tier '${tier}'; emitting standard defaults as a safety net" >&2
        emit_profile_keys "standard" "${vram_mb}" "${ram_gb}" "${gpu_name}" "${has_cuda}"
        ;;
    esac
}

# --- Main --------------------------------------------------------------------
main() {
    local mode="${1:-write}"

    local vram_mb ram_gb gpu_name has_cuda tier
    vram_mb=$(probe_vram_mb)
    ram_gb=$(probe_ram_gb)
    gpu_name=$(probe_gpu_name)
    has_cuda=$(probe_has_cuda)
    tier=$(classify_profile "${vram_mb}" "${ram_gb}")

    if [[ "${mode}" == "--print" ]]; then
        emit_profile_keys "${tier}" "${vram_mb}" "${ram_gb}" "${gpu_name}" "${has_cuda}"
        return 0
    fi

    # Write mode: install the conf into /etc/aurum/profile.conf atomically.
    # Use a temp file in the same directory so the rename is atomic on the
    # same filesystem; readers either see the previous version or the new one.
    install -d -m 0755 "$(dirname "${CONF_PATH}")"
    local tmp
    tmp="$(mktemp "${CONF_PATH}.XXXXXX")"
    emit_profile_keys "${tier}" "${vram_mb}" "${ram_gb}" "${gpu_name}" "${has_cuda}" > "${tmp}"
    chmod 0644 "${tmp}"
    mv -f "${tmp}" "${CONF_PATH}"
    echo "✓ AurumOS profile detected: ${tier} (VRAM=${vram_mb}MB, RAM=${ram_gb}GB, GPU=${gpu_name})"
    echo "  → ${CONF_PATH}"
}

main "$@"
