#pragma once
//
// ProfileClient — read-only accessor for /etc/aurum/profile.conf.
//
// The conf file is generated by distro/post-install/00-detect-profile.sh and
// regenerated on every boot by aurum-detect-profile.service. It contains
// bash-style KEY=VALUE pairs (optionally quoted). Wave 8 launcher scripts
// source it directly; the desktop side (Settings panel, dock, spotlight) goes
// through this client.
//
// Singleton because:
//   * the values are static for the lifetime of a session (the only writer is
//     a boot-time systemd unit); reparsing on every call would be wasteful.
//   * we want one consistent snapshot across all UI consumers in a process —
//     no risk of two QML pages disagreeing about VRAM mid-run.
//
// QML exposure: register as a context property on the settings app's
// QQmlContext (see desktop/settings/main.cpp). The object is a QObject so
// Q_INVOKABLE methods are reachable from QML directly.
//
#include <QObject>
#include <QString>
#include <QMap>
#include <mutex>

namespace aurum {

class ProfileClient : public QObject {
    Q_OBJECT
    Q_PROPERTY(QString profile      READ profile    CONSTANT)
    Q_PROPERTY(int     vramMb       READ vramMb     CONSTANT)
    Q_PROPERTY(int     ramGb        READ ramGb      CONSTANT)
    Q_PROPERTY(QString gpuName      READ gpuName    CONSTANT)
    Q_PROPERTY(bool    hasCuda      READ hasCuda    CONSTANT)

public:
    // Process-wide singleton. First call parses /etc/aurum/profile.conf (or
    // the override path in $AURUM_PROFILE_CONF, useful for tests and dev).
    static ProfileClient& instance();

    QString profile() const;          // e.g. "standard"
    int     vramMb()  const;          // 0 on CPU-only / detection failure
    int     ramGb()   const;
    QString gpuName() const;          // "none" if no GPU detected
    bool    hasCuda() const;

    // Generic getter for any AURUM_* key in the conf (returns `fallback` if
    // the key is absent). Lets QML / C++ consumers read newer keys without
    // touching this header every time the conf grows a field.
    Q_INVOKABLE QString get(const QString& key,
                            const QString& fallback = QString()) const;

    // Force a reparse. Useful after the user clicks "Re-detect" in the
    // HardwarePanel (which shells out to aurum-detect-profile and then asks
    // us to reload). Marked as a Q_INVOKABLE for QML.
    Q_INVOKABLE void reload();

private:
    ProfileClient();
    void parse(const QString& path);

    mutable std::mutex m_mu;
    QMap<QString, QString> m_kv;
    QString m_path;
};

} // namespace aurum
